apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-indexer-api
spec:
  replicas: 1 # Lower replicas for dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
spec:
  replicas: 1 # Single node for dev
