apiVersion: v1
kind: Namespace
metadata:
  name: log-indexer-dev
  labels:
    app: log-indexer
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: log-indexer-staging
  labels:
    app: log-indexer
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: log-indexer-prod
  labels:
    app: log-indexer
    environment: production
